---
- name: Install tree package
  ansible.builtin.apt:
    name: tree
    state: present
    update_cache: yes

- name: Copy custom configuration file
  ansible.builtin.copy:
    src: ./files/my_config.conf
    dest: /etc/myapp/my_config.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Set msg of tree configuration
  ansible.builtin.debug:
    msg: "{{ morpheus['customOptions']['msg_var'] }}"
